# Generated by Django 5.2.1 on 2025-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_alter_helloworld_code_alter_helloworld_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='helloworld',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
