# Generated by Django 5.2.1 on 2025-06-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_helloworld_latitude_helloworld_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helloworld',
            name='code',
        ),
        migrations.AddField(
            model_name='helloworld',
            name='problem_image',
            field=models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='問題点の写真'),
        ),
    ]
