# Generated by Django 5.2.1 on 2025-07-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_remove_helloworld_code_helloworld_problem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='problem_image',
            field=models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='自転車の写真'),
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_location', models.CharField(max_length=100, verbose_name='目撃場所')),
                ('sighting_datetime', models.DateTimeField(verbose_name='目撃日時')),
                ('sighting_image', models.ImageField(blank=True, null=True, upload_to='sightings/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
                ('theft_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='helloworld.helloworld', verbose_name='関連する盗難情報')),
            ],
        ),
    ]
