# Generated by Django 5.2.1 on 2025-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_alter_helloworld_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='解決済み'),
        ),
    ]
